#!/bin/bash

# get script install path
SCRIPTPATH=$( readlink -f -- "${0%/*}" )
cd $SCRIPTPATH

# check args
E_BADARGS=65
if [ "$#" -ne 2 ]
then
    echo "Usage: `basename $0` {password} {config_file}"
    exit $E_BADARGS
fi

# encrypt the provided password using jenkins own libraries
ENCRYPTED_PASSWORD=`java -jar /var/lib/jenkins/jenkins-cli.jar -s http://localhost:8080/ groovy PasswordEncrypt.groovy $1`

# replace any managerPassword line in the file specified
sed -i "/managerPassword/c\    <managerPasswordSecret>${ENCRYPTED_PASSWORD}</managerPasswordSecret>" $2

# save the manager password in a separate file for future use (config migration etc)
echo $ENCRYPTED_PASSWORD > managerPasswordSecret.txt
